[package]
name = "flint"
version = "0.9.0"
edition = "2024"


[dependencies]
anyhow = "1.0.98"
binrw = "0.15.0"
fs-err = "3.1.3"
rustix = { version = "1.0.8", features = [
    "fs",
    "process",
    "rand",
    "stdio",
    "system",
] }
paste = "1.0.15"
shrinkwraprs = "0.3.0"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
serde = { version = "1.0.228", features = ["derive"] }
bon = "3.8.1"
argh = "0.1.19"
envy = { workspace = true }
flint-pam = { version = "0.1.0", path = "../pam" }
hazymacros = { version = "0.1.0", path = "../../../../hazymacros" }
dyn-utils = "0.1.1"
zlink = "0.7.0"
pwd-grp = { version = "1.0.2", optional = true }
uuid = { version = "1.24.0", features = ["v7", "serde"] }
serde_json = "1.0.151"
static-reload = { git = "https://github.com/hazyfossa/static-reload", version = "0.1.0" }


[features]
logind = []
seatd = []

userdb = []
nss = []

systemd = ["logind", "userdb"]
pwd-grp = ["dep:pwd-grp"]
# pwd = ["dep:pwd-grp"]
