//! Generated code for Varlink interface `io.systemd.Login`.
//!
//! This code was generated by `zlink-codegen` from Varlink IDL.
//! You may prefer to adapt it, instead of using it verbatim.

//! APIs for managing login sessions.

use serde::{Deserialize, Serialize};
use zlink::{ReplyError, proxy};

/// Proxy trait for calling methods on the interface.
#[proxy("io.systemd.Login")]
pub trait Login {
    /// Allocates a new session.
    async fn create_session(
        &mut self,
        #[zlink(rename = "UID")] uid: i64,
        #[zlink(rename = "PID")] pid: Option<&ProcessId>,
        #[zlink(rename = "Type")] r#type: &SessionType,
        #[zlink(rename = "Class")] class: &SessionClass,
        #[zlink(rename = "Service")] service: Option<&str>,
        #[zlink(rename = "Desktop")] desktop: Option<&str>,
        #[zlink(rename = "Seat")] seat: Option<&str>,
        #[zlink(rename = "VTNr")] vt_nr: Option<i64>,
        #[zlink(rename = "TTY")] tty: Option<&str>,
        #[zlink(rename = "Display")] display: Option<&str>,
        #[zlink(rename = "Remote")] remote: Option<bool>,
        #[zlink(rename = "RemoteHost")] remote_host: Option<&str>,
        #[zlink(rename = "RemoteUser")] remote_user: Option<&str>,
        #[zlink(rename = "ExtraDeviceAccess")] extra_device_access: Option<&[&str]>,
    ) -> zlink::Result<Result<CreateSessionOutput<'_>, LoginError>>;
    /// Releases an existing session. Currently, will be refused unless originating from the session to release itself.
    async fn release_session(
        &mut self,
        #[zlink(rename = "Id")] id: Option<&str>,
    ) -> zlink::Result<Result<(), LoginError>>;
    /// Lists current sessions. If an Id or PID filter is provided, returns the single matching session; otherwise streams all current sessions (requires the 'more' flag).
    /// [Supports 'more' flag]
    async fn list_sessions(
        &mut self,
        #[zlink(rename = "Id")] id: Option<&str>,
        #[zlink(rename = "PID")] pid: Option<&ProcessId>,
    ) -> zlink::Result<Result<ListSessionsOutput, LoginError>>;
    /// Lists current users. If a UID or PID filter is provided, returns the single matching user; otherwise streams all current users (requires the 'more' flag).
    /// [Supports 'more' flag]
    async fn list_users(
        &mut self,
        #[zlink(rename = "UID")] uid: Option<i64>,
        #[zlink(rename = "PID")] pid: Option<&ProcessId>,
    ) -> zlink::Result<Result<ListUsersOutput, LoginError>>;
    /// Lists current seats. If an Id filter is provided, returns the single matching seat; otherwise streams all current seats (requires the 'more' flag).
    /// [Supports 'more' flag]
    async fn list_seats(
        &mut self,
        #[zlink(rename = "Id")] id: Option<&str>,
    ) -> zlink::Result<Result<ListSeatsOutput, LoginError>>;
    /// Lists all current inhibitors.
    /// [Requires 'more' flag]
    async fn list_inhibitors(&mut self) -> zlink::Result<Result<ListInhibitorsOutput, LoginError>>;
}

/// Output parameters for the CreateSession method.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CreateSessionOutput<'a> {
    #[serde(borrow)]
    #[serde(rename = "Id")]
    pub id: &'a str,
    #[serde(borrow)]
    #[serde(rename = "RuntimePath")]
    pub runtime_path: &'a str,
    #[serde(rename = "UID")]
    pub uid: i64,
    #[serde(borrow)]
    #[serde(rename = "Seat")]
    pub seat: Option<&'a str>,
    #[serde(rename = "VTNr")]
    pub vt_nr: Option<i64>,
    #[serde(rename = "Type")]
    pub r#type: SessionType,
    #[serde(rename = "Class")]
    pub class: SessionClass,
}

/// Output parameters for the ListSessions method.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ListSessionsOutput {
    pub context: SessionContext,
    pub runtime: SessionRuntime,
}

/// Output parameters for the ListUsers method.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ListUsersOutput {
    pub context: UserContext,
    pub runtime: UserRuntime,
}

/// Output parameters for the ListSeats method.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ListSeatsOutput {
    pub context: SeatContext,
    pub runtime: SeatRuntime,
}

/// Output parameters for the ListInhibitors method.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ListInhibitorsOutput {
    pub context: InhibitorContext,
    pub runtime: InhibitorRuntime,
}

/// Various types of sessions
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum SessionType {
    Unspecified,
    Tty,
    X11,
    Wayland,
    Mir,
    Web,
}

/// Various classes of sessions
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum SessionClass {
    /// Regular user sessions
    User,
    /// Session of the root user that shall be open for login from earliest moment on, and not be delayed for /run/nologin
    UserEarly,
    /// Regular user session whose home directory is not available right now, but will be later, at which point the session class can be upgraded to 'user'
    UserIncomplete,
    /// A user session that doesn't pull in the per-user service manager
    UserLight,
    /// The combination of user_early and user_light
    UserEarlyLight,
    /// Display manager greeter screen used for login
    Greeter,
    /// Similar, but a a lock screen
    LockScreen,
    /// Background session (that has no TTY, VT, Seat)
    Background,
    /// Similar, but for which no service manager is invoked
    BackgroundLight,
    /// The special session of the service manager
    Manager,
    /// The special session of the service manager for the root user
    ManagerEarly,
}

/// Inhibition mode
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum InhibitMode {
    /// Hard inhibition; blocks the operation entirely
    Block,
    /// Weak hard inhibition; like block, but the user who set it can override it without polkit authorization
    BlockWeak,
    /// Soft inhibition; delays the operation but ultimately permits it
    Delay,
}

/// Operations that can be inhibited
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum InhibitWhat {
    Shutdown,
    Sleep,
    Idle,
    HandlePowerKey,
    HandleSuspendKey,
    HandleHibernateKey,
    HandleLidSwitch,
    HandleRebootKey,
}

/// Process identifier
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ProcessId {
    /// Numeric UNIX PID value
    pub pid: i64,
    /// 64bit inode number of pidfd if known
    #[serde(rename = "pidfdId")]
    pub pidfd_id: Option<i64>,
    /// Boot ID of the system the inode number belongs to
    #[serde(rename = "bootId")]
    pub boot_id: Option<String>,
}

/// Dual timestamp
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Timestamp {
    /// Timestamp in µs in the CLOCK_REALTIME clock (wallclock)
    pub realtime: Option<i64>,
    /// Timestamp in µs in the CLOCK_MONOTONIC clock
    pub monotonic: Option<i64>,
}

/// Configuration aspects of a session (suitable for reuse as creation input)
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SessionContext {
    /// Numeric UNIX UID of the user owning this session
    #[serde(rename = "UID")]
    pub uid: i64,
    /// PID of the session leader
    #[serde(rename = "PID")]
    pub pid: Option<ProcessId>,
    /// The type of the session
    #[serde(rename = "Type")]
    pub r#type: SessionType,
    /// The class of the session
    #[serde(rename = "Class")]
    pub class: SessionClass,
    /// PAM service name
    #[serde(rename = "Service")]
    pub service: Option<String>,
    /// Desktop identifier
    #[serde(rename = "Desktop")]
    pub desktop: Option<String>,
    /// Seat this session is assigned to
    #[serde(rename = "Seat")]
    pub seat: Option<String>,
    /// Virtual terminal number of the session, if applicable
    #[serde(rename = "VTNr")]
    pub vt_nr: Option<i64>,
    /// TTY device of the session
    #[serde(rename = "TTY")]
    pub tty: Option<String>,
    /// X11 display of the session
    #[serde(rename = "Display")]
    pub display: Option<String>,
    /// Whether this is a remote session
    #[serde(rename = "Remote")]
    pub remote: Option<bool>,
    /// Remote host, if this is a remote session
    #[serde(rename = "RemoteHost")]
    pub remote_host: Option<String>,
    /// Remote user, if this is a remote session
    #[serde(rename = "RemoteUser")]
    pub remote_user: Option<String>,
    /// Device paths this session has special access to
    #[serde(rename = "ExtraDeviceAccess")]
    pub extra_device_access: Option<Vec<String>>,
}

/// Runtime state and dynamic information of a session
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SessionRuntime {
    /// The session identifier
    #[serde(rename = "Id")]
    pub id: String,
    /// systemd scope unit name
    #[serde(rename = "Scope")]
    pub scope: Option<String>,
    /// Audit session ID
    #[serde(rename = "Audit")]
    pub audit: Option<i64>,
    /// The session timestamps
    #[serde(rename = "Timestamp")]
    pub timestamp: Option<Timestamp>,
    /// Current state of the session
    #[serde(rename = "State")]
    pub state: String,
    /// Whether the session is active (i.e. in the foreground)
    #[serde(rename = "Active")]
    pub active: bool,
    /// Whether the session is idle
    #[serde(rename = "IdleHint")]
    pub idle_hint: bool,
    /// Timestamp when the session went idle, only present when IdleHint is true
    #[serde(rename = "IdleSinceHint")]
    pub idle_since_hint: Option<Timestamp>,
    /// Whether the session is currently locked
    #[serde(rename = "LockedHint")]
    pub locked_hint: bool,
    /// Whether this session class supports idle tracking
    #[serde(rename = "CanIdle")]
    pub can_idle: bool,
    /// Whether this session class supports locking
    #[serde(rename = "CanLock")]
    pub can_lock: bool,
}

/// Configuration aspects of a user
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct UserContext {
    /// Numeric UNIX UID
    #[serde(rename = "UID")]
    pub uid: i64,
    /// Numeric UNIX GID
    #[serde(rename = "GID")]
    pub gid: i64,
    /// User name
    #[serde(rename = "Name")]
    pub name: String,
    /// Whether lingering is enabled for this user
    #[serde(rename = "Linger")]
    pub linger: bool,
    /// Service manager unit name
    #[serde(rename = "Service")]
    pub service: Option<String>,
    /// User slice unit name
    #[serde(rename = "Slice")]
    pub slice: Option<String>,
    /// Path to the user's runtime directory
    #[serde(rename = "RuntimePath")]
    pub runtime_path: Option<String>,
}

/// Runtime state and dynamic information of a user
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct UserRuntime {
    /// Display session identifier
    #[serde(rename = "Display")]
    pub display: Option<String>,
    /// Current state of the user
    #[serde(rename = "State")]
    pub state: Option<String>,
    /// Identifiers of sessions belonging to this user
    #[serde(rename = "Sessions")]
    pub sessions: Option<Vec<String>>,
    /// Timestamp when the user was 'started' for the first time
    #[serde(rename = "Timestamp")]
    pub timestamp: Option<Timestamp>,
    /// Whether the user is idle
    #[serde(rename = "IdleHint")]
    pub idle_hint: bool,
    /// Timestamp when the user went idle, only present when IdleHint is true
    #[serde(rename = "IdleSinceHint")]
    pub idle_since_hint: Option<Timestamp>,
}

/// Configuration aspects of a seat
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SeatContext {
    /// The seat identifier
    #[serde(rename = "Id")]
    pub id: String,
}

/// Runtime state and dynamic information of a seat
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SeatRuntime {
    /// The currently active session on this seat, if any
    #[serde(rename = "ActiveSession")]
    pub active_session: Option<String>,
    /// Identifiers of sessions assigned to this seat
    #[serde(rename = "Sessions")]
    pub sessions: Option<Vec<String>>,
    /// Whether this seat supports text terminal sessions
    #[serde(rename = "CanTTY")]
    pub can_tty: bool,
    /// Whether this seat supports graphical sessions
    #[serde(rename = "CanGraphical")]
    pub can_graphical: bool,
    /// Whether the seat is idle
    #[serde(rename = "IdleHint")]
    pub idle_hint: bool,
    /// Timestamp when the seat went idle, only present when IdleHint is true
    #[serde(rename = "IdleSinceHint")]
    pub idle_since_hint: Option<Timestamp>,
}

/// Configuration aspects of an inhibitor
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct InhibitorContext {
    /// The inhibitor identifier
    #[serde(rename = "Id")]
    pub id: String,
    /// What is being inhibited
    #[serde(rename = "What")]
    pub what: Vec<InhibitWhat>,
    /// A human-readable descriptive string of who is taking the inhibition
    #[serde(rename = "Who")]
    pub who: Option<String>,
    /// A human-readable descriptive string of why the inhibition is taken
    #[serde(rename = "Why")]
    pub why: Option<String>,
    /// The inhibition mode
    #[serde(rename = "Mode")]
    pub mode: InhibitMode,
    /// The UID of the user taking the inhibition
    #[serde(rename = "UID")]
    pub uid: i64,
}

/// Runtime state and dynamic information of an inhibitor
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct InhibitorRuntime {
    /// The PID of the process taking the inhibition
    #[serde(rename = "PID")]
    pub pid: Option<ProcessId>,
    /// The inhibitor timestamps
    #[serde(rename = "Since")]
    pub since: Option<Timestamp>,
}

/// Errors that can occur in this interface.
#[derive(Debug, Clone, PartialEq, ReplyError)]
#[zlink(interface = "io.systemd.Login")]
pub enum LoginError {
    /// No session by this name found
    NoSuchSession,
    /// No seat by this name found
    NoSuchSeat,
    /// No user by this UID found
    NoSuchUser,
    /// No inhibitor found
    NoSuchInhibitor,
    /// Process already member of a session
    AlreadySessionMember,
    /// The specified virtual terminal (VT) is already taken by another session
    VirtualTerminalAlreadyTaken,
    /// Maximum number of sessions reached
    TooManySessions,
    /// Failed to allocate a unit for the session
    UnitAllocationFailed,
    /// The session leader process does not have a pidfd
    NoSessionPidfd,
}
